export default ({
    "AF": "Afganistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "Samoa Amerykańskie",
    "AD": "Andora",
    "AO": "Angola",
    "AI": "Anguilla",
    "AG": "Antigua i Barbuda",
    "AR": "Argentna",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbejdżan",
    "BS": "Bahamy",
    "BD": "Bangladessz",
    "BB": "Barbados",
    "BY": "Białoruś",
    "BE": "Belgia",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermudy",
    "BT": "Bhutan",
    "BO": "Boliwia",
    "BA": "Bośnia i Hercegowina",
    "BW": "Botswana",
    "BR": "Brazylia",
    "IO": "Brytyjskie Terytorium Oceanu Indyjskiego",
    "BG": "Bułgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Kambodża",
    "CM": "Kamerun",
    "CA": "Kanada",
    "CV": "Republika Zielonego Przylądka",
    "KY": "Kajmany",
    "CF": "Republika Środkowoafrykańska",
    "TD": "Czad",
    "CL": "Chile",
    "CN": "Chiny",
    "CO": "Kolumbia",
    "KM": "Komory",
    "CG": "Kongo",
    "CD": "Demokratyczna republika Konga",
    "CK": "Wyspy Cooka",
    "CR": "Kostaryka",
    "CI": "Wybrzeże Kości Słoniowej",
    "HR": "Chorwacja",
    "CU": "Kuba",
    "CW": "Curaçao",
    "CY": "Cypr",
    "CZ": "Czechy",
    "DK": "Dania",
    "DJ": "Dżibuti",
    "DM": "Dominika",
    "DO": "Dominikana",
    "EC": "Ekwador",
    "EG": "Egipt",
    "SV": "Salwador",
    "GQ": "Gwinea Równikowa",
    "ER": "Erytrea",
    "EE": "Estonia",
    "ET": "Etiopia",
    "FK": "Falklandy (Malwiny)",
    "FO": "Wyspy Owcze",
    "FJ": "Fidżi",
    "FI": "Finlandia",
    "FR": "Francja",
    "PF": "Polinezja Francuska",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Gruzja",
    "DE": "Niemcy",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Grecja",
    "GL": "Grenlandia",
    "GD": "Grenada",
    "GU": "Guam",
    "GT": "Gwatemala",
    "GG": "Guernsey",
    "GN": "Gwinea",
    "GW": "Guinea Bissau",
    "HT": "Haiti",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Węgru",
    "IS": "Islandia",
    "IN": "Indie",
    "ID": "Indonezja",
    "IR": "Iran",
    "IQ": "Irak",
    "IE": "Irlandia",
    "IM": "Wyspa Man",
    "IL": "Izrael",
    "IT": "Włochy",
    "JM": "Jamajka",
    "JP": "Japonia",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazachstan",
    "KE": "Kenia",
    "KI": "Kiribati",
    "KP": "Północna Korea",
    "KR": "Południowa Korea",
    "KW": "Kuweit",
    "KG": "Kirgistan",
    "LA": "Laos",
    "LV": "Łotwa",
    "LB": "Liban",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libia",
    "LI": "Liechtenstein",
    "LT": "Litwa",
    "LU": "Luxembourg",
    "MO": "Makau",
    "MK": "Macedonia (BJRM)",
    "MG": "Madagaskar",
    "MW": "Malawi",
    "MY": "Malezja",
    "MV": "Malediwy",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Wyspy Marshalla",
    "MQ": "Martynika",
    "MR": "Mauretania",
    "MU": "Mauritius",
    "MX": "Meksyk",
    "FM": "Mikronezja",
    "MD": "Mołdawia",
    "MC": "Monako",
    "MN": "Mongolia",
    "ME": "Czarnogóra",
    "MS": "Montserrat",
    "MA": "Maroko",
    "MZ": "Mozambik",
    "MM": "Mjanma",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Holandia",
    "NZ": "Nowa Zealandia",
    "NI": "Nikaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk",
    "MP": "Mariany Północne",
    "NO": "Norwegia",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Terytoria palestyńskie",
    "PA": "Panama",
    "PG": "Papua-Nowa Gwinea",
    "PY": "Paragwaj",
    "PE": "Peru",
    "PH": "Filipiny",
    "PN": "Pitcairn",
    "PL": "Polska",
    "PT": "Portugalia",
    "PR": "Portoryko",
    "QA": "Katar",
    "RO": "Ruminia",
    "RU": "Rosja",
    "RW": "Rwanda",
    "KN": "Saint Kitts i Nevis",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Wyspy Świętego Tomasza i Książęca",
    "SA": "Arabia Saudyjska",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seszele",
    "SL": "Sierra Leone",
    "SG": "Singapur",
    "SX": "Sint Maarten",
    "SK": "Słowacja",
    "SI": "Słowenia",
    "SB": "Wyspy Salomona",
    "SO": "Somalia",
    "ZA": "Południowa Afryka",
    "SS": "Sudan Południowy",
    "ES": "Hiszpania",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Surinam",
    "SZ": "Eswatini",
    "SE": "Szwecja",
    "CH": "Szwajcaria",
    "SY": "Syria",
    "TW": "Tajwan",
    "TJ": "Tadżykistan",
    "TZ": "Tanzania",
    "TH": "Tajlandia",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trynidad i Tobago",
    "TN": "Tunezja",
    "TR": "Turcja",
    "TM": "Turkmenistan",
    "TC": "Turks i Caicos",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraina",
    "AE": "Zjednoczone Emiraty Arabskie",
    "GB": "Wielka brytania",
    "US": "Stany Zjednoczone",
    "UY": "Urugwaj",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Wenezuela",
    "VN": "Wietnam",
    "VI": "Wyspy Dziewicze Stanów Zjednoczonych",
    "YE": "Jemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
});
